
# service id
ID = 3
# service name
Name = "Global"
# nats agent url
NatsUrl = "nats://0.0.0.0:4222"
# if expose is true, it's a outgoing service.
Expose = false
Addr = "0.0.0.0"
Port = 0
FPS = 0
Debug = false
DebugPort = 0

# depend other services
# [[Depend]]
# Name = ""
# Count = 1

# custom args
# [Args]
# Key = "value"
